[theme]
primaryColor = "#d32f2f"
backgroundColor = "#f4f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideTopBar = true
